CREATE SCHEMA MARATHON_TICKETS;

CREATE TABLE IF NOT EXISTS MARATHON_TICKETS.users (
    ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    USERNAME VARCHAR(255) NOT NULL ,
    PASSWORD VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS MARATHON_TICKETS.TICKETS (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    FIRSTNAME VARCHAR(255)  NOT NULL ,
    LASTNAME VARCHAR(255) NOT NULL,
    CLUB VARCHAR(255),
    DISTANCE VARCHAR(255),
    PRIMARY KEY (id)
 )